# Generated by Django 5.2.4 on 2025-07-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storiesmodel',
            name='archive_path',
            field=models.FileField(upload_to='storage/'),
        ),
    ]
