# Generated by Django 5.2.4 on 2025-07-16 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userd_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_as_user', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_recived', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
